name: 'NPM Pakage version update and commit'
description: 'NPM Pakage version update and commit'
inputs:
  what-to-do:  # id of input
    description: 'What to Do'
    required: true
    default: 'NPM Pakage version update and commit'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/config.sh
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
